version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_db
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      default:
        aliases:
          - localhost

  app:
    build: .
    container_name: car_app
    ports:
      - "8085:8080"
    depends_on:
      - mysql